/// Flutter icons CustomIcons1
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons1
///      fonts:
///       - asset: fonts/CustomIcons1.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons1 {
  CustomIcons1._();

  static const _kFontFam = 'CustomIcons1';

  static const IconData user = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fingerprint =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData at = const IconData(0xe805, fontFamily: _kFontFam);
}
